# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uListItem.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ListWidgetItem(object):
    def setupUi(self, ListWidgetItem):
        ListWidgetItem.setObjectName("ListWidgetItem")
        ListWidgetItem.resize(542, 86)
        self.horizontalLayoutWidget = QtWidgets.QWidget(ListWidgetItem)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 541, 81))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.map_l = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.map_l.sizePolicy().hasHeightForWidth())
        self.map_l.setSizePolicy(sizePolicy)
        self.map_l.setMaximumSize(QtCore.QSize(100, 100))
        self.map_l.setObjectName("map_l")
        self.horizontalLayout.addWidget(self.map_l)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_fullpath = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_fullpath.setObjectName("label_fullpath")
        self.verticalLayout.addWidget(self.label_fullpath)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_name = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_name.setObjectName("label_name")
        self.horizontalLayout_2.addWidget(self.label_name)
        self.label_arch = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_arch.setObjectName("label_arch")
        self.horizontalLayout_2.addWidget(self.label_arch)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.label_status = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_status.setObjectName("label_status")
        self.horizontalLayout_2.addWidget(self.label_status)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(ListWidgetItem)
        QtCore.QMetaObject.connectSlotsByName(ListWidgetItem)

    def retranslateUi(self, ListWidgetItem):
        _translate = QtCore.QCoreApplication.translate
        ListWidgetItem.setWindowTitle(_translate("ListWidgetItem", "Form"))
        self.map_l.setText(_translate("ListWidgetItem", "TextLabel"))
        self.label_fullpath.setText(_translate("ListWidgetItem", "Full Path"))
        self.label_name.setText(_translate("ListWidgetItem", "ProductName"))
        self.label_arch.setText(_translate("ListWidgetItem", "X64"))
        self.label_5.setText(_translate("ListWidgetItem", "* 星"))
        self.label_status.setText(_translate("ListWidgetItem", "----"))
