# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'XSignWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 440, 751, 101))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 761, 431))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 0, 741, 391))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.listWidget = QtWidgets.QListWidget(self.formLayoutWidget)
        self.listWidget.setObjectName("listWidget")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.listWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnRtkSign = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btnRtkSign.setObjectName("btnRtkSign")
        self.horizontalLayout.addWidget(self.btnRtkSign)
        self.btnMSSign = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btnMSSign.setObjectName("btnMSSign")
        self.horizontalLayout.addWidget(self.btnMSSign)
        self.btnExtract = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btnExtract.setObjectName("btnExtract")
        self.horizontalLayout.addWidget(self.btnExtract)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.te_etl = QtWidgets.QTextEdit(self.tab_2)
        self.te_etl.setGeometry(QtCore.QRect(50, 30, 601, 31))
        self.te_etl.setMarkdown("")
        self.te_etl.setObjectName("te_etl")
        self.te_pdb = QtWidgets.QTextEdit(self.tab_2)
        self.te_pdb.setGeometry(QtCore.QRect(50, 70, 601, 31))
        self.te_pdb.setObjectName("te_pdb")
        self.textEdit_3 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_3.setGeometry(QtCore.QRect(50, 120, 601, 191))
        self.textEdit_3.setObjectName("textEdit_3")
        self.pb_peel = QtWidgets.QPushButton(self.tab_2)
        self.pb_peel.setGeometry(QtCore.QRect(50, 350, 101, 28))
        self.pb_peel.setObjectName("pb_peel")
        self.pb_stripdir = QtWidgets.QPushButton(self.tab_2)
        self.pb_stripdir.setGeometry(QtCore.QRect(660, 70, 93, 28))
        self.pb_stripdir.setObjectName("pb_stripdir")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.btnRtkSign.setText(_translate("MainWindow", "RTK Sign"))
        self.btnMSSign.setText(_translate("MainWindow", "MS Sign"))
        self.btnExtract.setText(_translate("MainWindow", "解压"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Sign"))
        self.pb_peel.setText(_translate("MainWindow", "Convert"))
        self.pb_stripdir.setText(_translate("MainWindow", "ExtratDir"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Log"))
